apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-01
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx_with_mt
  template:
    metadata:
      labels:
        app: nginx_with_mt
    spec:
      containers:
      - name: nginx
        image: nginx:1.20
        ports:
        - containerPort: 80
      - name: multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "3080"
        - name: HTTPS_PORT
          value: "3443"
        ports:
        - containerPort: 3080
          name: mt1
        - containerPort: 3443
          name: mt2

---

apiVersion: v1
kind: Service
metadata:
  name: web-svc
spec:
  ports:
    - name: nginx
      port: 80
      protocol: TCP
      targetPort: 80
    - name: miltitool
      port: 3080
      protocol: TCP
      targetPort: 3080
  selector:
    app: nginx_with_mt

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: multitool
  name: pod-multitool
spec:
  containers:
  - image: wbitt/network-multitool
    imagePullPolicy: IfNotPresent
    name: multitool